name: Test and build a new apk
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: subosito/flutter-action@v2
       with:
         channel: stable
     - name: Install dependencies
       run: flutter pub get
     - name: Test code
       run: flutter test
     - name: Build apk
       if: ${{ success() }}
       run: flutter build apk
     - uses: actions/upload-artifact@v4
       if: ${{ success() }}
       with:
         name: download build artifact
         path: build/app/outputs/flutter-apk/app-release.apk
     - name: Send email to team members
       if: ${{ success() }}
       uses: dawidd6/action-send-mail@v3
       with:
         server_port: 465
         secure: true
         server_address: smtp.gmail.com
         username: noyoule@gmail.com
         password: yqnl zhst ycmx fnzv
         from: noyoule@gmail.com
         to: victoirenoyouliwa@gmail.com
         subject: "completed successfully by ${{github.actor}}"
         body: "All test has past. A new realease has been updated at https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} go to download it"
     - name: automerge
       if: ${{ github.event_name == 'pull_request' }}
       uses: "pascalgn/automerge-action@v0.16.2"
       env:
         GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    